name: XC8 Compile Check

# Runs on pushes to pull request
on: pull_request

jobs:
  xc8-compile-check:
    name: XC8 Compile Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install XC8
        run: |
          wget https://ww1.microchip.com/downloads/aemDocuments/documents/DEV/ProductDocuments/SoftwareTools/xc8-v3.00-full-install-linux-x64-installer.run
          chmod +x ./xc8-v3.00-full-install-linux-x64-installer.run
          sudo ./xc8-v3.00-full-install-linux-x64-installer.run --mode unattended  --netservername localhost --debuglevel 4
          
      - name: Run Compile
        run: |
          PATH=$PATH:/opt/microchip/xc8/v3.00/bin/ make
